package compiler

import (
	"bytes"
	"fmt"
)

// Generate transpiles a transform AST into a Go+TinyGo source file. The
// generated file is a build artifact (never hand-edited): the YAML transform
// remains the source of truth (arch §4.1).
func Generate(t *Transform) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by the weavster transform compiler. DO NOT EDIT.\n")
	b.WriteString("// Source of truth: the YAML transform; this file is a rebuildable artifact.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("// transform implements the guest ABI: input bytes are at [ptr, ptr+length);\n")
	b.WriteString("// output is written in place and the output length returned.\n")
	b.WriteString("//go:export transform\n")
	b.WriteString("func transform(ptr uint32, length uint32) uint32 {\n")
	b.WriteString("\t_ = ptr\n\t_ = length\n")

	if len(t.Steps) > 0 {
		b.WriteString("\tsteps := []step{\n")
		for _, s := range t.Steps {
			b.WriteString("\t\t")
			writeStep(&b, s)
			b.WriteString(",\n")
		}
		b.WriteString("\t}\n\t_ = steps\n")
	}

	b.WriteString("\treturn length\n")
	b.WriteString("}\n\n")
	b.WriteString("// step encodes a declarative transform step.\n")
	b.WriteString("type step struct {\n\tkind, from, to, expr string\n}\n")
	return b.Bytes(), nil
}

func writeStep(b *bytes.Buffer, s Step) {
	switch {
	case s.Map != nil:
		fmt.Fprintf(b, "{kind: %q, from: %q, to: %q}", "map", s.Map.From, s.Map.To)
	case s.Set != nil:
		fmt.Fprintf(b, "{kind: %q, to: %q, expr: %q}", "set", s.Set.Field, s.Set.Expr)
	case s.Filter != nil:
		fmt.Fprintf(b, "{kind: %q, expr: %q, to: %q}", "filter", s.Filter.When, s.Filter.Action)
	case s.Build != nil:
		fmt.Fprintf(b, "{kind: %q, expr: %q}", "build", s.Build.Template)
	case s.DestinationSet != nil:
		fmt.Fprintf(b, "{kind: %q, to: %q}", "destinationSet", joinComma(s.DestinationSet.Exclude))
	default:
		fmt.Fprintf(b, "{kind: %q}", "empty")
	}
}

func joinComma(vals []string) string {
	out := ""
	for i, v := range vals {
		if i > 0 {
			out += ","
		}
		out += v
	}
	return out
}
