# Codecov Configuration for Weavster
# Enforces high code coverage standards

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: 100%
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "src/"
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "src/"

  ignore:
    - "tests/"
    - "docs/"
    - "scripts/"
    - "**/__pycache__/"
    - "**/conftest.py"
    - "temp*.md"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  branches:
    - main
    - release/**
    - develop

github_checks:
  annotations: true

flags:
  unit:
    paths:
      - src/
    carryforward: false
