site_name: weavster
repo_url: https://github.com/weavster-dev/weavster
site_url: https://weavster-dev.github.io/weavster
site_description: Weavster is a cloud-native integration platform that brings declarative simplicity to data pipelines of all sizes.
site_author: Gregory Hunt
edit_uri: edit/main/docs/
repo_name: weavster-dev/weavster
copyright: Maintained by <a href="https://weavster.dev">weavster-dev</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/weavster"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/weavster-dev/weavster
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/weavster

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
