import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Flow } from '@weavster/core';
import { build } from 'esbuild';
import { collectModules } from './functions.js';
import { loadFlow } from './flow.js';

// @weavster/core and esbuild resolve from the CLI's own node_modules. Under
// `platform: 'neutral'` esbuild ignores the `main` field, so the bundle is
// resolved from the CLI install location regardless of the user's cwd.
const cliNodeModules = `${dirname(fileURLToPath(import.meta.url))}/../node_modules`;

/** Runtime hazards a QuickJS/Javy sandbox bundle must not contain (the S1 guard). */
const HAZARDS: Record<string, RegExp> = {
  'node: builtin': /from\s*['"]node:|require\(['"]node:/,
  'bare require()': /\brequire\s*\(/,
  'process.': /\bprocess\./,
  async: /\basync\b/,
  await: /\bawait\b/,
  Promise: /\bPromise\b/,
  setTimeout: /\bsetTimeout\b/,
};

/**
 * The generated per-flow entry module. It bakes in the flow's steps and wires
 * its `_ts` functions, exposes `handle(input)` over the WASM envelope contract
 * (see docs/ARTIFACT_SPEC.md), and — under Javy — drives it over stdin/stdout.
 */
export function generateEntry(flow: Flow, modules: string[]): string {
  const imports = modules.map((name, i) => `import fn_${i} from './functions/${name}';`).join('\n');
  const registry = modules.map((name, i) => `  ${JSON.stringify(name)}: fn_${i},`).join('\n');

  return `// Generated by \`weavster compile\` — do not edit.
import { applyFlow, json, xml } from '@weavster/core';
${imports}

// QuickJS/Javy has no structuredClone; the canonical model is JSON-shaped, so a
// JSON round-trip is a faithful clone.
globalThis.structuredClone ??= (v) =>
  v === undefined ? undefined : JSON.parse(JSON.stringify(v));

const flow = ${JSON.stringify(flow)};
const functions = {
${registry}
};
const parsers = { json: json.parse, xml: xml.parse };
const serializers = { json: json.serialize, xml: xml.serialize };

export function handle(input) {
  let doc;
  try {
    doc = parsers[input.in](input.payload);
  } catch (e) {
    return { ok: false, error: { stage: 'parse', type: e.name, message: e.message } };
  }
  let out;
  try {
    out = applyFlow(doc, flow, { functions });
  } catch (e) {
    return { ok: false, error: { stage: 'transform', type: e.name, message: e.message } };
  }
  try {
    return { ok: true, payload: serializers[input.out](out) };
  } catch (e) {
    return { ok: false, error: { stage: 'serialize', type: e.name, message: e.message } };
  }
}

// Javy ABI: whole-buffer stdin in, result envelope on stdout. Guarded so the
// bundle stays importable in Node (for tests) where Javy is absent.
if (typeof Javy !== 'undefined') {
  const input = JSON.parse(readInput());
  writeOutput(JSON.stringify(handle(input)));
}

function readInput() {
  const chunks = [];
  const buf = new Uint8Array(4096);
  let total = 0;
  let n;
  while ((n = Javy.IO.readSync(0, buf)) > 0) {
    chunks.push(buf.slice(0, n));
    total += n;
  }
  const all = new Uint8Array(total);
  let at = 0;
  for (const c of chunks) {
    all.set(c, at);
    at += c.length;
  }
  return new TextDecoder().decode(all);
}

function writeOutput(text) {
  const bytes = new TextEncoder().encode(text);
  let at = 0;
  while (at < bytes.length) {
    at += Javy.IO.writeSync(1, bytes.subarray(at));
  }
}
`;
}

export interface BundleResult {
  /** The QuickJS-safe ESM bundle, or null if generation/guard failed. */
  code: string | null;
  errors: string[];
}

/** Scan bundled code for sandbox hazards; returns a list of offending names. */
function guardHazards(code: string): string[] {
  return Object.entries(HAZARDS)
    .filter(([, re]) => re.test(code))
    .map(([name]) => name);
}

/** Bundle one flow into a single QuickJS-safe ESM module ready for Javy. */
export async function bundleFlow(projectDir: string, flowName: string): Promise<BundleResult> {
  const { flow, errors } = loadFlow(projectDir, flowName);
  if (flow === null) return { code: null, errors: errors.map((e) => `${flowName}: ${e}`) };

  const modules = collectModules(flow.steps);
  const entry = generateEntry(flow, modules);

  let code: string;
  try {
    const result = await build({
      stdin: { contents: entry, resolveDir: projectDir, loader: 'js' },
      bundle: true,
      format: 'esm',
      platform: 'neutral',
      target: 'es2020',
      write: false,
      nodePaths: [cliNodeModules],
      mainFields: ['module', 'main'],
      conditions: ['import', 'module', 'default'],
      plugins: [
        {
          name: 'forbid-node-builtins',
          setup(b) {
            b.onResolve({ filter: /^node:/ }, (args) => ({
              errors: [{ text: `node: builtin not allowed in a flow bundle: ${args.path}` }],
            }));
          },
        },
      ],
    });
    code = result.outputFiles[0].text;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { code: null, errors: [`${flowName}: bundle failed: ${message}`] };
  }

  const hazards = guardHazards(code);
  if (hazards.length > 0) {
    return {
      code: null,
      errors: [`${flowName}: bundle is not sandbox-safe: ${hazards.join(', ')}`],
    };
  }
  return { code, errors: [] };
}
