name: Manual Release (Legacy)

on:
  release:
    types: [published]

jobs:
  legacy-publish:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
